# Generated by Django 6.0.2 on 2026-02-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Room Number'),
        ),
    ]
